name: thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - jupyter
  - notebook
  - pip:
    - torch>=2.0.0
    - tensorflow>=2.15.0
    - keras>=3.0.0
    - numpy>=1.24.0,<2.0.0
    - pandas>=2.0.0
    - matplotlib>=3.7.0
    - pyserial>=3.5
    - vpython>=7.6.0

